[package]
name = "hesabdari-asan"
version = "4.0.0"
description = "Hesabdari Asan v2 native free edition"
authors = ["MNRAHIMI . Ltd"]
edition = "2021"

[lib]
name = "hesabdari_asan_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
chrono = { version = "0.4", features = ["clock"] }
sha2 = "0.10"
base64 = "0.22"
